# Flash Visualization Code


In [2]:
%matplotlib notebook
import yt
yt.toggle_interactivity()

In [6]:
for i in range (1,6):
    ds = yt.load(
        f"/home/oppenheimer/RelBlastwave/Sedov/sedov_hdf5_chk_{i:04d}")

    print(ds.field_list)

    #make a slice plot
    slc = yt.SlicePlot(ds, 'z', 'dens')
    #plot density along x-axis
    
    # slc.set_cmap('density'', 'viridis')
    # slc.set_zlim('density', -1, 1)
    slc.annotate_title("Density Slice")
    slc.save(f"density_slice{i:04d}.png")


yt : [INFO     ] 2025-06-03 21:53:49,101 Parameters: current_time              = 0.010059905419357001
yt : [INFO     ] 2025-06-03 21:53:49,102 Parameters: domain_dimensions         = [8 8 1]
yt : [INFO     ] 2025-06-03 21:53:49,103 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-06-03 21:53:49,103 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2025-06-03 21:53:49,104 Parameters: cosmological_simulation   = 0
yt : [INFO     ] 2025-06-03 21:53:49,355 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:49,356 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:49,357 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:49,358 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:49,359 Making a fixed resolution buffer of (('flash', 'dens')) 800 by 800


[('flash', 'dena'), ('flash', 'dens'), ('flash', 'eina'), ('flash', 'eint'), ('flash', 'ener'), ('flash', 'enra'), ('flash', 'gamc'), ('flash', 'game'), ('flash', 'pres'), ('flash', 'prsa'), ('flash', 'shok'), ('flash', 'temp'), ('flash', 'velx'), ('flash', 'vely'), ('flash', 'velz'), ('flash', 'vlxa'), ('flash', 'vlya'), ('flash', 'vlza')]


yt : [INFO     ] 2025-06-03 21:53:49,733 Saving plot density_slice0001.png
yt : [INFO     ] 2025-06-03 21:53:49,949 Parameters: current_time              = 0.020050605635410303
yt : [INFO     ] 2025-06-03 21:53:49,950 Parameters: domain_dimensions         = [8 8 1]
yt : [INFO     ] 2025-06-03 21:53:49,951 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-06-03 21:53:49,952 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2025-06-03 21:53:49,953 Parameters: cosmological_simulation   = 0
yt : [INFO     ] 2025-06-03 21:53:50,195 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:50,196 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:50,198 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:50,198 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:50,200 Making a fixed resolution buffer of (('flash', 'dens')) 800 by 800


[('flash', 'dena'), ('flash', 'dens'), ('flash', 'eina'), ('flash', 'eint'), ('flash', 'ener'), ('flash', 'enra'), ('flash', 'gamc'), ('flash', 'game'), ('flash', 'pres'), ('flash', 'prsa'), ('flash', 'shok'), ('flash', 'temp'), ('flash', 'velx'), ('flash', 'vely'), ('flash', 'velz'), ('flash', 'vlxa'), ('flash', 'vlya'), ('flash', 'vlza')]


yt : [INFO     ] 2025-06-03 21:53:50,447 Saving plot density_slice0002.png
yt : [INFO     ] 2025-06-03 21:53:50,816 Parameters: current_time              = 0.030166051242147225
yt : [INFO     ] 2025-06-03 21:53:50,817 Parameters: domain_dimensions         = [8 8 1]
yt : [INFO     ] 2025-06-03 21:53:50,817 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-06-03 21:53:50,818 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2025-06-03 21:53:50,818 Parameters: cosmological_simulation   = 0
yt : [INFO     ] 2025-06-03 21:53:51,219 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:51,220 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:51,222 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:51,222 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:51,225 Making a fixed resolution buffer of (('flash', 'dens')) 800 by 800


[('flash', 'dena'), ('flash', 'dens'), ('flash', 'eina'), ('flash', 'eint'), ('flash', 'ener'), ('flash', 'enra'), ('flash', 'gamc'), ('flash', 'game'), ('flash', 'pres'), ('flash', 'prsa'), ('flash', 'shok'), ('flash', 'temp'), ('flash', 'velx'), ('flash', 'vely'), ('flash', 'velz'), ('flash', 'vlxa'), ('flash', 'vlya'), ('flash', 'vlza')]


yt : [INFO     ] 2025-06-03 21:53:51,490 Saving plot density_slice0003.png
yt : [INFO     ] 2025-06-03 21:53:51,677 Parameters: current_time              = 0.04005200785426079
yt : [INFO     ] 2025-06-03 21:53:51,677 Parameters: domain_dimensions         = [8 8 1]
yt : [INFO     ] 2025-06-03 21:53:51,678 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-06-03 21:53:51,678 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2025-06-03 21:53:51,679 Parameters: cosmological_simulation   = 0
yt : [INFO     ] 2025-06-03 21:53:52,053 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:52,054 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:52,056 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:52,057 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:52,059 Making a fixed resolution buffer of (('flash', 'dens')) 800 by 800


[('flash', 'dena'), ('flash', 'dens'), ('flash', 'eina'), ('flash', 'eint'), ('flash', 'ener'), ('flash', 'enra'), ('flash', 'gamc'), ('flash', 'game'), ('flash', 'pres'), ('flash', 'prsa'), ('flash', 'shok'), ('flash', 'temp'), ('flash', 'velx'), ('flash', 'vely'), ('flash', 'velz'), ('flash', 'vlxa'), ('flash', 'vlya'), ('flash', 'vlza')]


yt : [INFO     ] 2025-06-03 21:53:52,320 Saving plot density_slice0004.png
yt : [INFO     ] 2025-06-03 21:53:52,512 Parameters: current_time              = 0.05016158899765282
yt : [INFO     ] 2025-06-03 21:53:52,513 Parameters: domain_dimensions         = [8 8 1]
yt : [INFO     ] 2025-06-03 21:53:52,514 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-06-03 21:53:52,514 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2025-06-03 21:53:52,515 Parameters: cosmological_simulation   = 0
yt : [INFO     ] 2025-06-03 21:53:52,887 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:52,888 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:52,890 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:52,891 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 21:53:52,893 Making a fixed resolution buffer of (('flash', 'dens')) 800 by 800


[('flash', 'dena'), ('flash', 'dens'), ('flash', 'eina'), ('flash', 'eint'), ('flash', 'ener'), ('flash', 'enra'), ('flash', 'gamc'), ('flash', 'game'), ('flash', 'pres'), ('flash', 'prsa'), ('flash', 'shok'), ('flash', 'temp'), ('flash', 'velx'), ('flash', 'vely'), ('flash', 'velz'), ('flash', 'vlxa'), ('flash', 'vlya'), ('flash', 'vlza')]


yt : [INFO     ] 2025-06-03 21:53:53,141 Saving plot density_slice0005.png


In [5]:
import yt
import numpy as np
import matplotlib.pyplot as plt
from unyt import unyt_quantity
# /home/oppenheimer/RelBlastwave/Sedov/sedov_hdf5_chk_0000
# Initialize lists to store time and radius values
times = []
radii = []

for i in range(1, 5):
    ds = yt.load(f"/home/oppenheimer/RelBlastwave/Sedov/sedov_hdf5_chk_{i:04d}")
    
    print(ds.field_list)
    
    # Get the current simulation time (with units)
    current_time = ds.current_time
    times.append(current_time)
    
    # Create a sphere to find maximum density location
    # Use proper units for the center
    center = ds.arr([0.5, 0.5, 0.5], "code_length")
    sp = ds.sphere(center, (0.5, "code_length"))
    
    # Find the point of maximum density (returns position with units)
    max_dens_loc = sp.argmax('density')
    
    # Calculate distance from center (radius) - properly handle units
    radius = np.sqrt(np.sum((max_dens_loc - center)**2))
    radii.append(radius)
    
    # Make a slice plot (optional)
    slc = yt.SlicePlot(ds, 'z', 'temperature')
    slc.annotate_title(f"Temperature Slice, t = {current_time:.2f}")
    slc.save(f"temperature_slice{i:04d}.png")

# Convert to numpy arrays for plotting, stripping units if needed
times = np.array([t.value for t in times])
radii = np.array([r.value for r in radii])

# Get the time units for axis labels
time_units = str(times[0].units) if hasattr(times[0], 'units') else 'code_time'
radius_units = str(radii[0].units) if hasattr(radii[0], 'units') else 'code_length'

# Plot r vs t
plt.figure(figsize=(8,6))
plt.plot(times, radii, 'bo-', label='Simulation Data')
plt.xlabel(f'Time [{time_units}]')
plt.ylabel(f'Radius [{radius_units}]')
plt.title('Sedov-Taylor Blast Wave 2D: Radius vs Time')
plt.grid(True)
plt.legend()

# Optional: Plot theoretical Sedov-Taylor scaling (r ∝ t^(2/5))
if len(times) > 1:
    # Fit a power law to see if we get the expected 2/5 exponent
    fit = np.polyfit(np.log(times[1:]), np.log(radii[1:]), 1)
    plt.plot(times, np.exp(fit[1]) * times**fit[0], 'r--', 
             label=f'Fit: r ∝ t^{fit[0]:.2f} (Expected 0.5)')
    plt.legend()

plt.savefig('radius_vs_time.png')
plt.show()

yt : [INFO     ] 2025-06-03 16:56:12,885 Parameters: current_time              = 0.015502052631918548
yt : [INFO     ] 2025-06-03 16:56:12,886 Parameters: domain_dimensions         = [8 8 1]
yt : [INFO     ] 2025-06-03 16:56:12,887 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-06-03 16:56:12,887 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2025-06-03 16:56:12,888 Parameters: cosmological_simulation   = 0
yt : [INFO     ] 2025-06-03 16:56:13,204 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 16:56:13,205 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 16:56:13,207 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 16:56:13,207 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 16:56:13,209 Making a fixed resolution buffer of (('gas', 'temperature')) 800 by 800


[('flash', 'dena'), ('flash', 'dens'), ('flash', 'eina'), ('flash', 'eint'), ('flash', 'ener'), ('flash', 'enra'), ('flash', 'gamc'), ('flash', 'game'), ('flash', 'pres'), ('flash', 'prsa'), ('flash', 'shok'), ('flash', 'temp'), ('flash', 'velx'), ('flash', 'vely'), ('flash', 'velz'), ('flash', 'vlxa'), ('flash', 'vlya'), ('flash', 'vlza')]


yt : [INFO     ] 2025-06-03 16:56:13,698 Saving plot temperature_slice0001.png
yt : [INFO     ] 2025-06-03 16:56:13,965 Parameters: current_time              = 0.02665692231930248
yt : [INFO     ] 2025-06-03 16:56:13,966 Parameters: domain_dimensions         = [8 8 1]
yt : [INFO     ] 2025-06-03 16:56:13,967 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-06-03 16:56:13,968 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2025-06-03 16:56:13,968 Parameters: cosmological_simulation   = 0
yt : [INFO     ] 2025-06-03 16:56:14,292 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 16:56:14,293 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 16:56:14,296 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 16:56:14,297 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 16:56:14,298 Making a fixed resolution buffer of (('gas', 'temperature')) 800 by 800


[('flash', 'dena'), ('flash', 'dens'), ('flash', 'eina'), ('flash', 'eint'), ('flash', 'ener'), ('flash', 'enra'), ('flash', 'gamc'), ('flash', 'game'), ('flash', 'pres'), ('flash', 'prsa'), ('flash', 'shok'), ('flash', 'temp'), ('flash', 'velx'), ('flash', 'vely'), ('flash', 'velz'), ('flash', 'vlxa'), ('flash', 'vlya'), ('flash', 'vlza')]


yt : [INFO     ] 2025-06-03 16:56:14,589 Saving plot temperature_slice0002.png
yt : [INFO     ] 2025-06-03 16:56:14,821 Parameters: current_time              = 0.048966661694070344
yt : [INFO     ] 2025-06-03 16:56:14,822 Parameters: domain_dimensions         = [8 8 1]
yt : [INFO     ] 2025-06-03 16:56:14,823 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-06-03 16:56:14,823 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2025-06-03 16:56:14,824 Parameters: cosmological_simulation   = 0
yt : [INFO     ] 2025-06-03 16:56:15,217 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 16:56:15,218 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 16:56:15,220 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 16:56:15,221 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 16:56:15,222 Making a fixed resolution buffer of (('gas', 'temperature')) 800 by 800


[('flash', 'dena'), ('flash', 'dens'), ('flash', 'eina'), ('flash', 'eint'), ('flash', 'ener'), ('flash', 'enra'), ('flash', 'gamc'), ('flash', 'game'), ('flash', 'pres'), ('flash', 'prsa'), ('flash', 'shok'), ('flash', 'temp'), ('flash', 'velx'), ('flash', 'vely'), ('flash', 'velz'), ('flash', 'vlxa'), ('flash', 'vlya'), ('flash', 'vlza')]


yt : [INFO     ] 2025-06-03 16:56:15,514 Saving plot temperature_slice0003.png
yt : [INFO     ] 2025-06-03 16:56:15,760 Parameters: current_time              = 0.09358614044360608
yt : [INFO     ] 2025-06-03 16:56:15,761 Parameters: domain_dimensions         = [8 8 1]
yt : [INFO     ] 2025-06-03 16:56:15,762 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-06-03 16:56:15,763 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2025-06-03 16:56:15,763 Parameters: cosmological_simulation   = 0
yt : [INFO     ] 2025-06-03 16:56:16,216 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 16:56:16,216 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 16:56:16,218 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 16:56:16,219 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-06-03 16:56:16,220 Making a fixed resolution buffer of (('gas', 'temperature')) 800 by 800


[('flash', 'dena'), ('flash', 'dens'), ('flash', 'eina'), ('flash', 'eint'), ('flash', 'ener'), ('flash', 'enra'), ('flash', 'gamc'), ('flash', 'game'), ('flash', 'pres'), ('flash', 'prsa'), ('flash', 'shok'), ('flash', 'temp'), ('flash', 'velx'), ('flash', 'vely'), ('flash', 'velz'), ('flash', 'vlxa'), ('flash', 'vlya'), ('flash', 'vlza')]


yt : [INFO     ] 2025-06-03 16:56:16,501 Saving plot temperature_slice0004.png


<IPython.core.display.Javascript object>

In [10]:
for i in range (0,6):
    ds = yt.load(
        f"/home/oppenheimer/RelBlastwave/Sedov/sedov_hdf5_chk_{i:04d}")

    print(ds.domain_dimensions)


    #make a slice plot
    slc = yt.SlicePlot(ds, 'z', 'temperature')
    #plot density along x-axis
    
    # slc.set_cmap('density'', 'viridis')
    # slc.set_zlim('density', -1, 1)
    slc.annotate_title("Temperature Slice")
    slc.save(f"temperature_slice{i:04d}.png")


# #make a LinePlot
# for i in range (0,6):
#     ds = yt.load(
#         f"/home/oppenheimer/RelBlastwave/Sedov/sedov_hdf5_chk_{i:04d}")

#     print(ds.field_list)

#     #make a slice plot
#     # slc = yt.LinePlot(ds,'density',[0,0],[1,0],100)
#     # Create a line along the x-axis at y = center of domain
#     center = ds.domain_center
#     start_point = [ds.domain_left_edge[0], center[1], center[2]]
#     end_point = [ds.domain_right_edge[0], center[1], center[2]]

#     line = yt.LinePlot(ds, "temperature", start_point, end_point, 512)
#     # line.save()

#     # slc.set_cmap('density'', 'viridis')
#     # slc.set_zlim('density', -1, 1)
#     # slc.annotate_title("Density Line")
#     line.save(f"temperature_line{i:04d}.png")

# #make a projection plot

yt : [INFO     ] 2025-05-01 21:15:48,080 Parameters: current_time              = 0.0
yt : [INFO     ] 2025-05-01 21:15:48,081 Parameters: domain_dimensions         = [8 8 1]
yt : [INFO     ] 2025-05-01 21:15:48,082 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-05-01 21:15:48,082 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2025-05-01 21:15:48,083 Parameters: cosmological_simulation   = 0


[8 8 1]


yt : [INFO     ] 2025-05-01 21:15:48,295 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:48,296 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:48,297 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:48,298 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:48,300 Making a fixed resolution buffer of (('gas', 'temperature')) 800 by 800
yt : [INFO     ] 2025-05-01 21:15:48,571 Saving plot temperature_slice0000.png
yt : [INFO     ] 2025-05-01 21:15:48,777 Parameters: current_time              = 0.010059905419357001
yt : [INFO     ] 2025-05-01 21:15:48,779 Parameters: domain_dimensions         = [8 8 1]
yt : [INFO     ] 2025-05-01 21:15:48,780 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-05-01 21:15:48,781 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2025-05-01 21:15:48,781 Parameters: cosmological_simulation   = 0


[8 8 1]


yt : [INFO     ] 2025-05-01 21:15:49,226 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:49,227 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:49,229 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:49,229 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:49,231 Making a fixed resolution buffer of (('gas', 'temperature')) 800 by 800
yt : [INFO     ] 2025-05-01 21:15:49,534 Saving plot temperature_slice0001.png
yt : [INFO     ] 2025-05-01 21:15:49,753 Parameters: current_time              = 0.020050605635410303
yt : [INFO     ] 2025-05-01 21:15:49,754 Parameters: domain_dimensions         = [8 8 1]
yt : [INFO     ] 2025-05-01 21:15:49,755 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-05-01 21:15:49,755 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2025-05-01 21:15:49,756 Parameters: cosmological_simulation   = 0


[8 8 1]


yt : [INFO     ] 2025-05-01 21:15:50,002 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:50,003 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:50,005 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:50,005 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:50,007 Making a fixed resolution buffer of (('gas', 'temperature')) 800 by 800
yt : [INFO     ] 2025-05-01 21:15:50,446 Saving plot temperature_slice0002.png
yt : [INFO     ] 2025-05-01 21:15:50,637 Parameters: current_time              = 0.030166051242147225
yt : [INFO     ] 2025-05-01 21:15:50,638 Parameters: domain_dimensions         = [8 8 1]
yt : [INFO     ] 2025-05-01 21:15:50,638 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-05-01 21:15:50,639 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2025-05-01 21:15:50,640 Parameters: cosmological_simulation   = 0


[8 8 1]


yt : [INFO     ] 2025-05-01 21:15:50,881 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:50,882 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:50,883 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:50,884 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:50,885 Making a fixed resolution buffer of (('gas', 'temperature')) 800 by 800
yt : [INFO     ] 2025-05-01 21:15:51,149 Saving plot temperature_slice0003.png
yt : [INFO     ] 2025-05-01 21:15:51,464 Parameters: current_time              = 0.04005200785426079
yt : [INFO     ] 2025-05-01 21:15:51,465 Parameters: domain_dimensions         = [8 8 1]
yt : [INFO     ] 2025-05-01 21:15:51,465 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-05-01 21:15:51,466 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2025-05-01 21:15:51,466 Parameters: cosmological_simulation   = 0


[8 8 1]


yt : [INFO     ] 2025-05-01 21:15:51,703 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:51,704 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:51,706 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:51,707 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:51,708 Making a fixed resolution buffer of (('gas', 'temperature')) 800 by 800
yt : [INFO     ] 2025-05-01 21:15:51,983 Saving plot temperature_slice0004.png
yt : [INFO     ] 2025-05-01 21:15:52,168 Parameters: current_time              = 0.05016158899765282
yt : [INFO     ] 2025-05-01 21:15:52,169 Parameters: domain_dimensions         = [8 8 1]
yt : [INFO     ] 2025-05-01 21:15:52,170 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-05-01 21:15:52,171 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2025-05-01 21:15:52,171 Parameters: cosmological_simulation   = 0


[8 8 1]


yt : [INFO     ] 2025-05-01 21:15:52,540 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:52,541 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:52,543 xlim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:52,544 ylim = 0.000000 1.000000
yt : [INFO     ] 2025-05-01 21:15:52,545 Making a fixed resolution buffer of (('gas', 'temperature')) 800 by 800
yt : [INFO     ] 2025-05-01 21:15:52,811 Saving plot temperature_slice0005.png


In [7]:
#create gifs from the pngs
import imageio
import glob

# Collect and sort the image filenames
image_filenames = sorted(glob.glob("density_slice*.png"))

# Create the GIF
with imageio.get_writer('density_slice_evolution.gif', mode='I', duration=15, loop=0) as writer:
    for filename in image_filenames:
        image = imageio.imread(filename)
        writer.append_data(image)


/tmp/ipykernel_17225/1754614713.py:11: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  image = imageio.imread(filename)
